### ISSUE TITLE
Encapsulate "amazingsalary" field in Film.class

### ISSUE THREAD

**Issue by miguelrteixeira** [arthurportas/rumos-academia-java#1]
Encapsulate amazingsalary field in Film.class

**Comment by andresousaribeiro** [comment]
Fix!

**Comment by miguelrteixeira** [comment]
field must be private

**Comment by andresousaribeiro** [comment]
@arthurportas already fix the problem. commit f5d6ce268c349aa9ab273e05438c5ccf8dc79397
